image: maven:3.8.1-jdk-11

stages:
    - test
    - tag_version

variables:
    GIT_STRATEGY: clone

test:
    stage: test
    script:
        - echo "Running tests"
    only:
        - merge_requests

tag_version:
    stage: tag_version
    script:
        - echo "Extracting version from pom.xml"
        - export VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        - echo "Tagging version $VERSION"
        - git config --global user.email "oleksandr.nikolaichuk@privatbank.ua"
        - git config --global user.name "dn070578noi"
        - git tag -a $VERSION -m "Tagging version $VERSION"
        - git push https://gitlab-ci-token:${GITLAB_ACCESS_TOKEN}@git.privatbank.ua/DN171M000004/dn171m000004_20/tf-avbo/utility/xlsx_to_db.git $VERSION
        - echo "Tagged version $VERSION"
    only:
        - main
    except:
        - tags
