stages:
    - build
    - release

variables:
    MAVEN_CLI_OPTS: "-B -U -DskipTests"

before_script:
    - 'export PATH=$PATH:$CI_PROJECT_DIR/.m2/repository/org/apache/maven/plugins/maven-release-plugin/3.0.0-M1'

build:
    stage: build
    script:
        - mvn $MAVEN_CLI_OPTS clean install

release:
    stage: release
    script:
        - mvn $MAVEN_CLI_OPTS release:prepare -DreleaseVersion=1.1.1 -Dtag=1.1.1 -DdevelopmentVersion=1.1.2-SNAPSHOT
        - mvn $MAVEN_CLI_OPTS release:perform
    only:
        - release_test
