image: maven:3.6.3-jdk-11

stages:
    - test
    - tag_version

variables:
    GIT_STRATEGY: clone

test:
    stage: test
    script:
        - echo "Running tests"
        - ./mvnw test
    only:
        - merge_requests

tag_version:
    stage: tag_version
    script:
        - echo "Extracting version from pom.xml"
        - export VERSION=$(sed -n 's|.*<version>\(.*\)</version>.*|\1|p' pom.xml | head -n 1)
        - echo "Tagging version $VERSION"
        - git config --global user.email "sekator778@gmail.com"
        - git config --global user.name "sekator778"
        - export COMMIT_HASH=$(git rev-parse HEAD)
        - export TAG_MESSAGE="Release version $VERSION based on commit $COMMIT_HASH"
        - git tag -a "$VERSION" -m "$TAG_MESSAGE" "$COMMIT_HASH"
        - git push https://gitlab-ci-token:${GITLAB_ACCESS_TOKEN}@github.com/sekator778/xlsx-to-db.git $VERSION
        - echo "Tagged version $VERSION"
    only:
        - main
    except:
        - tags
