image: maven:3.6.3-jdk-11

stages:
    - test
    - tag_version

variables:
    GIT_STRATEGY: clone

test:
    stage: test
    script:
        - echo "Running tests"
    only:
        - merge_requests

tag_version:
    stage: tag_version
    script:
        - echo "Extracting version from pom.xml"
        - export VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        - echo "Tagging version $VERSION"
        - git config --global user.email "oleksandr.nikolaichuk@privatbank.ua"
        - git config --global user.name "dn070578noi"
        - export COMMIT_HASH=$(git rev-parse HEAD)
        - export TAG_MESSAGE="Release version $VERSION based on commit $COMMIT_HASH"
        - git tag -a "$VERSION" -m "$TAG_MESSAGE" "$COMMIT_HASH"
        - git push origin "$VERSION"
        - echo "Tagged version $VERSION"
    only:
        - main
    except:
        - tags
